git clone https://github.com/nzakas/cssembed.git
git clone https://github.com/elevenetc/InteractiveCanvas.git
git clone https://github.com/ippontech/tatami.git
git clone https://github.com/puniverse/galaxy.git
git clone https://github.com/wangdan/AisenForAndroid.git
git clone https://github.com/mgrzechocinski/dagger2-example.git
git clone https://github.com/boundlessgeo/GeoGig.git
git clone https://github.com/rajasharan/RearrangeableLayout.git
git clone https://github.com/tajchert/BusWear.git
git clone https://github.com/iammert/FastGCM.git
git clone https://github.comhttps://github.com/contact.git
git clone https://github.com/jacobtabak/Fragment-Switcher.git
git clone https://github.com/pizza/MaterialTabs.git
git clone https://github.com/brucetoo/VideoControllerView.git
git clone https://github.com/cagataygurturk/lambadaframework.git
git clone https://github.com/rawr/rawr.git
git clone https://github.com/jxcore/jxm.git
git clone https://github.com/henrytao-me/android-md-core.git
git clone https://github.com/allegro/grunt-maven-plugin.git
git clone https://github.com/bmeike/ProgrammingAndroidExamples.git
git clone https://github.com/googlearchive/solutions-mobile-backend-starter-java.git
git clone https://github.com/koush/Widgets.git
git clone https://github.com/depoll/bindroid.git
git clone https://github.com/dgmltn/Android-ShareEverywhere.git
git clone https://github.com/jenkinsci/android-emulator-plugin.git
git clone https://github.com/damellis/cellphone.git
git clone https://github.com/xuningjack/select_picture_module.git
git clone https://github.com/damnhandy/Handy-URI-Templates.git
git clone https://github.com/colintheshots/AnDevCon-RxPatterns.git
git clone https://github.com/erickok/mimicry.git
git clone https://github.com/JorgeCastilloPrz/Dagger2Scopes.git
git clone https://github.com/Rogero0o/MissView.git
git clone https://github.com/spring-projects/grails-data-mapping.git
git clone https://github.com/skyscreamer/yoga.git
git clone https://github.com/foursquare/fongo.git
git clone https://github.com/Startappz/DobSliding.git
git clone https://github.com/nenick/AndroidStudioAndRobolectric.git
git clone https://github.com/luohaha/jlitespider.git
git clone https://github.com/goodev/SquareGridView.git
git clone https://github.com/foursquare/fongo.git
git clone https://github.com/Startappz/DobSliding.git
git clone https://github.com/nenick/AndroidStudioAndRobolectric.git
git clone https://github.com/luohaha/jlitespider.git
git clone https://github.com/goodev/SquareGridView.git
git clone https://github.com/flavienlaurent/colorpicker.git
git clone https://github.com/chiuki/android-swipe-image-viewer.git
git clone https://github.com/wqandroid/ihepai.git
git clone https://github.com/liaohuqiu/SimpleHashSet.git
git clone https://github.com/jiang111/ObservableScheduler.git
git clone https://github.com/skyscreamer/yoga.git
git clone https://github.com/foursquare/fongo.git
git clone https://github.com/Startappz/DobSliding.git
